version: '3'
services:
        web:
                image: kernel_tdt
                build: .
                ports:
                        - "8060:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8060_tdtSite/volumes
